# Assignment: Week 5
# Name: Mather, Brandon
# Date: 2022-07-06

names(df_data)
#1)
  #1)
library(dplyr)
library(readxl)
setwd("~/Documents/GitHub/fantastic-disco/DSC520data")
housing_data <- read_excel('Copy of week-6-housing.xlsx')
df_data <- data.frame(housing_data)
df_data %>% group_by(zip5)
summarize(df_data, sale_price = mean(Sale.Price))
mutate(df_data, total_bathrooms = bath_full_count + bath_3qtr_count + bath_half_count)
df_data %>% filter(is.na(sale_warning))
select(df_data, starts_with("zi"))
df_arrange_data <- arrange(df_data, zip5)
  #2)
library(purrr)
discard(df_data, is.na)
compact(df_data)
  #3)
bathrooms_total <- c(3, 3, 3, 2, 2)
new_house <- c(1/3/06, 70000, 1, 3,)
df_data_new <- cbind(df_data, bathrooms_total)
df_data_new2 <- rbind(df_data, new_house)
  #4)
df_data_split <- strsplit(df_data, split=",")
paste(df_data_split, collapse=",")
